### ISSUE TITLE
ERROR: Unexpected exception occurred while performing groovy command.

### ISSUE THREAD

**Issue by mtvann** [samrocketman/jenkins-bootstrap-slack#6]
I'm using this script to configure Slack on a new Jenkins instance, and am getting the below error using configure-slack.groovy.  It appears to be failing at the call to `slack.configure(req, formData)`, but I'm unable to figure out why.  Any idea what might be the issue?

```
ERROR: Unexpected exception occurred while performing groovy command.
java.lang.UnsupportedOperationException
at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:52)
at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
at com.sun.proxy.$Proxy68.bindJSON(Unknown Source)
at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.configure(SlackNotifier.java:492)
at jenkins.plugins.slack.SlackNotifier$DescriptorImpl$configure.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
at RemoteClass.run(RemoteClass:26)
at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
at groovy.lang.GroovyShell.run(GroovyShell.java:518)
at groovy.lang.GroovyShell.run(GroovyShell.java:497)
at hudson.cli.GroovyCommand.run(GroovyCommand.java:89)
at hudson.cli.CLICommand.main(CLICommand.java:283)
at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
at hudson.remoting.UserRequest.perform(UserRequest.java:212)
at hudson.remoting.UserRequest.perform(UserRequest.java:54)
at hudson.remoting.Request$2.run(Request.java:369)
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:66)
at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

```

**Comment by mtvann** [comment]
I am calling the script after Jenkins is installed using the following command `java -jar jenkins-cli.jar -remoting -s http://localhost:8080 groovy configure-slack.groovy`.  The weird thing is that it has worked pretty well with new deployments for over a year and there have been no changes.  Only thing that may have changed is the version of Jenkins (now 2.138.3-1.1) or the Slack notification plugin (2.4)

**Comment by mtvann** [comment]
Actually this version worked for me: [https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/configure-slack.groovy](https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/configure-slack.groovy), so I'm closing this.

**Comment by samrocketman** [comment]
Ah yeah, I haven't tried messing with this jenkins-bootstrapper in quite some time.  I should probably update it at some point, though, I don't really use it.
